#
#   Copyright (C) 2021 Reiko Asakura. All Rights Reserved.
#
#   Vita Development Suite Samples
#

name: Build

on:
  push:
  schedule:
    - cron: '0 10 * * *'

env:
  SCE_ROOT_DIR: ${{ github.workspace }}/ci-base/SCE
  SCE_PSP2_SDK_DIR: ${{ github.workspace }}/ci-base/sdk
  SCE_GIMCONV: ${{ github.workspace }}/ci-base/GimConv/GimConv.exe

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout CI base
        uses: actions/checkout@v2
        with:
          repository: Vita-Development-Suite/ci-base
          path: ci-base
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Install dependencies
        run: |
          $ProgressPreference = "SilentlyContinue"
          "psp2-cmake-toolchains","cmake-modules","toolchain","libraries"
            | ForEach-Object {
                $base_path = "https://bin.shotatoshounenwachigau.moe/vdsuite"
                Invoke-WebRequest -Uri "$base_path/vdsuite-$_-latest.zip" -OutFile "$_.zip"
                Expand-Archive -Path "$_.zip" -DestinationPath ${{ github.workspace }}/ci-base
              }

      - name: Build (Make)
        env:
          CMAKE_GENERATOR: MinGW Makefiles
        run: |
          cmake . -B "build-${{ env.CMAKE_GENERATOR }}"
          if ($LastExitCode -ne 0) { exit $LastExitCode }
          cmake --build "build-${{ env.CMAKE_GENERATOR }}" --parallel "$((Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors)"

      - name: Install Ninja
        uses: Vita-Development-Suite/gha-setup-ninja@master

      - name: Build (Ninja)
        env:
          CMAKE_GENERATOR: Ninja
        run: |
          cmake . -B "build-${{ env.CMAKE_GENERATOR }}"
          if ($LastExitCode -ne 0) { exit $LastExitCode }
          cmake --build "build-${{ env.CMAKE_GENERATOR }}"

      - name: Build (Ninja Multi-Config)
        env:
          CMAKE_GENERATOR: Ninja Multi-Config
        run: |
          cmake . -B "build-${{ env.CMAKE_GENERATOR }}"
          if ($LastExitCode -ne 0) { exit $LastExitCode }
          cmake --build "build-${{ env.CMAKE_GENERATOR }}" --config Debug
          if ($LastExitCode -ne 0) { exit $LastExitCode }
          cmake --build "build-${{ env.CMAKE_GENERATOR }}" --config Release
